name: DevOpsCICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' # we tell Github to only execute this step if we're on our development branch (so we don't put unfinished branches in production)
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install # installs dependencies
      - run: npm test # runs tests
      - run: npm run lint # runs linting
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.PASSWORD  }}
          USER_NAME: ${{ secrets.USERNAME  }}
        run: |
          echo "$PRIVATE_KEY" > devops.pem
          chmod 400 devops.pem
          ssh -o "StrictHostKeyChecking=no" -i devops.pem ubuntu@18.237.95.107 "cd /home/ubuntu/production/devops && sudo git pull && sudo npm install && pm2 restart all"
        env:
          CI: true # shows terminal output!

     
